package gui;
import intermedio.CuadTable;
import intermedio.Cuadruplo;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import parser.VbParserWrapper;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Armando
 */
public class IDE extends javax.swing.JFrame {

	/**
	 * Creates new form ide
	 */
	public IDE() {
		initComponents();
		this.rTextScrollPane1.setLineNumbersEnabled(true);
		this.rTextScrollPane1.setFoldIndicatorEnabled(true);
		this.editor.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_VISUAL_BASIC);
		this.editor.getDocument().addDocumentListener(new EditorDocumentListener());
		this.editor.addParser(new VbParserWrapper(this.editor, this.output));
		this.editor.setText("Sub Main()\n\nEnd Sub");
	}
	
	public RSyntaxTextArea getrSyntaxTextArea(){
		return this.editor;
	}
	
	private class EditorDocumentListener implements DocumentListener{

		@Override
		public void insertUpdate(DocumentEvent de) {
			setPendingText();
		}

		@Override
		public void removeUpdate(DocumentEvent de) {
			setPendingText();
		}

		@Override
		public void changedUpdate(DocumentEvent de) {
			setPendingText();
		}
		
		private void setPendingText(){
			IDE.output.setForeground(Color.lightGray);
			IDE.output.setText("parsing...");
		}
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        rTextScrollPane1 = new org.fife.ui.rtextarea.RTextScrollPane();
        editor = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);
        jSplitPane1.setOneTouchExpandable(true);

        output.setColumns(20);
        output.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        output.setForeground(new java.awt.Color(255, 0, 0));
        output.setRows(5);
        output.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outputMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(output);

        jSplitPane1.setBottomComponent(jScrollPane1);

        editor.setColumns(20);
        editor.setRows(5);
        rTextScrollPane1.setViewportView(editor);

        jSplitPane1.setLeftComponent(rTextScrollPane1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver CI");
        jMenu3.setRolloverEnabled(false);
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputMouseClicked

    }//GEN-LAST:event_outputMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
		CIViewer viewer = new CIViewer();
		viewer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		viewer.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

	
	/**
	 * @param args the command line arguments
	 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static org.fife.ui.rsyntaxtextarea.RSyntaxTextArea editor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private static javax.swing.JTextArea output;
    private org.fife.ui.rtextarea.RTextScrollPane rTextScrollPane1;
    // End of variables declaration//GEN-END:variables
}
