
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 18 22:25:42 CST 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 11;
  public static final int True = 40;
  public static final int Coma = 36;
  public static final int End = 24;
  public static final int Until = 19;
  public static final int ByRef = 30;
  public static final int If = 20;
  public static final int Id = 43;
  public static final int InicioDeLinea = 46;
  public static final int Sub = 32;
  public static final int IntLiteral = 59;
  public static final int Menos = 4;
  public static final int Mas = 3;
  public static final int Concatenar = 45;
  public static final int Menor = 7;
  public static final int Else = 22;
  public static final int Por = 5;
  public static final int Mayor = 8;
  public static final int Then = 21;
  public static final int Punto = 37;
  public static final int While = 18;
  public static final int To = 13;
  public static final int Ampersand = 55;
  public static final int CambioDeLinea = 44;
  public static final int For = 12;
  public static final int EOF = 0;
  public static final int Step = 14;
  public static final int Not = 9;
  public static final int Function = 33;
  public static final int And = 10;
  public static final int error = 1;
  public static final int False = 50;
  public static final int Entre = 6;
  public static final int As = 31;
  public static final int Integer = 25;
  public static final int Private = 57;
  public static final int Char = 27;
  public static final int ParI = 38;
  public static final int Do = 17;
  public static final int ElseIf = 23;
  public static final int StrLiteral = 60;
  public static final int Public = 56;
  public static final int ParD = 39;
  public static final int MenorIgual = 49;
  public static final int Dim = 2;
  public static final int FinDeLinea = 58;
  public static final int String = 28;
  public static final int Input = 53;
  public static final int Writeln = 35;
  public static final int MayorIgual = 48;
  public static final int Type = 54;
  public static final int ByVal = 29;
  public static final int Call = 51;
  public static final int NuevaLinea = 47;
  public static final int Boolean = 26;
  public static final int Write = 34;
  public static final int Exit = 52;
  public static final int Next = 15;
  public static final int Loop = 16;
  public static final int Igual = 42;
  public static final int GuionBajo = 41;
}

